apiVersion: v1
kind: Service
metadata:
  name: workout-service
  labels:
    zone: dev
    version: v1
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30000
      protocol: TCP
  selector:
    app: workout-server
